### PR TITLE
PSMDB-1038 Release notes for 5.0.8-7

### PR DESCRIPTION
**Pull request by nastena1606**
modified:   source/conf.py
	new file:   source/release_notes/5.0.8-7.rst
	modified:   source/release_notes/index.rst

### CODE REVIEW

**Review by igorsol — APPROVED** [review]
LGTM

**Comment by kwilktx** [comment]
Change the wording to this:

"[SERVER-63387](https://jira.mongodb.org/browse/SERVER-63387) - Fixed the order of backup blocks returned to the user to match the order retrieved from WiredTiger."

**Comment by kwilktx** [comment]
Change the wording to this:
"[SERVER-63531](https://jira.mongodb.org/browse/SERVER-63531) - Fixed the issue with a commitQuorum incorrectly allowing non-voting buildIndexes:false nodes to be included in the commitQuorum count. It also fixed an error message relating to data-bearing nodes and quorum regarding to non-voting nodes."

**Comment by kwilktx** [comment]
Change the wording to this:
"[SERVER-65261](https://jira.mongodb.org/browse/SERVER-65261) - Fixed the issue reporting an incorrect number of documents deleted from a capped collection when utilizing a collection scan to perform the delete action."

**Comment by kwilktx** [comment]
Change the wording to this:
"[WT-8924](https://jira.mongodb.org/browse/WT-8924) - Fixed a bug that causes replication to stall on secondary replica set members in a sharded cluster handling cross-shard transactions. It is caused by WiredTger to erroneously return a write conflict when deciding if an update to a record is allowed. If MongoDB decides to retry the operation that caused the conflict in WiredTiger, it will enter an indefinite retry loop, and oplog application will stall on secondary nodes. 

If this bug is hit, the secondary nodes will experience indefinite growth in replication lag. Restart the secondary nodes to resume replication.

This bug affects MongoDB 4.4.10 through 4.4.13 and 5.0.4 to 5.0.7.
Update to the latest version to avoid the secondary replication stall and lag issues."

**Comment by kwilktx** [comment]
Once the above changes have been made, these release notes are approved.

Regards,
Kimberly

**Review by kwilktx — APPROVED** [review]
Once the provided changes have been added, approved.

**Review by igorsol — APPROVED** [review]
LGTM

**Pull request merged**
