### PR TITLE
PSMDB-1029 Release notes 5.0.7-6

### PR DESCRIPTION
**Pull request by nastena1606**
modified:   source/conf.py
	new file:   source/release_notes/5.0.7-6.rst
	modified:   source/release_notes/index.rst

### CODE REVIEW

**Review by igorsol — APPROVED** [review]

**Review by spron-in — APPROVED** [review]

**Review by sandraromanchenko — APPROVED** [review]

**Comment by kwilktx** [comment]
Anastasia,

As provided in slack, here is feedback after review

This is really the 1st version of 5.0.x that does not have multiple potentially data loss or corruption causing bugs.

I would add a note similar to something like the following -
"Due to the number of potential serious bugs in earlier upstream versions of MongoDB Community v5.0.x, this version (v5.0.7-6) is the 1st version that is deemed to be production capable."

**Comment by kwilktx** [comment]
Of the bugs fixed in this version v5.0.7, these are a few of the more critical ones:

`SERVER-63203	 Chunk splitter never splits if more than 8192 split points are found - jumbo chunks, disk imbalance, performance problems	https://jira.mongodb.org/browse/SERVER-63203
SERVER-64517		https://jira.mongodb.org/browse/SERVER-64517
SERVER-64403	when we are trying to perform the collation-encoding of a document with a missing sort attribute. In this case an invariant is violated and mongod crashes.	https://jira.mongodb.org/browse/SERVER-64403
SERVER-63722	rename collection (sharding step) can get stuck 	`

**Comment by kwilktx** [comment]
Fix formatting under Release highlights section.

Thanks!

**Comment by kwilktx** [comment]
Approved once edits around the above notes are completed.

**Pull request merged**
