### PR TITLE
PSMDB-1113 Release notes 5.0.10-9

### PR DESCRIPTION
**Pull request by nastena1606**
modified:   source/conf.py
	new file:   source/release_notes/5.0.10-9.rst
	modified:   source/release_notes/index.rst

### CODE REVIEW

**Review by igorsol — APPROVED** [review]
LGTM

**Comment by kwilktx** [comment]
Change the Opening Release Highlight phrase to the following:

Release Highlights
This release includes bug fixes and  improvements provided by MongoDB and included in Percona Server for MongoDB. It specifically includes multiple fixes relate to sharding and the sharing operation. Bugs of note are the following:

xxxxxx
xxxxx

Change this:
[SERVER-66418](https://jira.mongodb.org/browse/SERVER-66418) - Fixed the issue with bad projection created during dependency analysis due to string order assumption. It resulted in the PathCollision error error. The issue is fixed by improving dependency analysis for projections by folding dependencies into ancestor dependencies where possible

  to this:
  
  "[SERVER-66418](https://jira.mongodb.org/browse/SERVER-66418) - Fixed the issue with bad projection created during dependency analysis due to string order assumption. It resulted in the PathCollision error. The issue is fixed by improving dependency analysis for projections by folding dependencies into ancestor dependencies where possible"

**Comment by kwilktx** [comment]
Add the following sharding and resharding related bugs to the list please:


https://jira.mongodb.org/browse/SERVER-67457
SERVER-67457 - Fixed the situation where the shards may skip certain steps in the resharding process but respond to the resharding coordinator as if they had. This can cause the resharding coordinator to continue to wait for updated states in the config.reshardingOperations document on the primary config server and stall indefinitelty


https://jira.mongodb.org/browse/SERVER-66866
SERVER-66866 - Fixed the potential for the range deleter to wait unnecessarily during concurrent migrations between batches

https://jira.mongodb.org/browse/SERVER-66727
SERVER-66727 Fixes problem where 2 very different measurements (one in the past and one in future)  could be incorrectly included in the same buckettime-series bucket

https://jira.mongodb.org/browse/SERVER-66046
SERVER-66046 - Fixes the problem where the resharding coordinator won’t automatically abort when a recipient shard encounters errors and must abort

https://jira.mongodb.org/browse/SERVER-64433
SERVER-64433 - Resolves potential problem when adding or removing shards and incorrectly gossiping a new topology time without it being majorly committed

**Review by kwilktx — APPROVED** [review]
As expected there were a few more bugs to call out.
Add the changes provided in the comments and should be good to go.

Thank you!

**Review by spron-in — APPROVED** [review]

**Pull request merged**
