### PR TITLE
PSMDB-373-update-docs-hashicorp-vault-support updated text and variants

### PR DESCRIPTION
**Pull request by patrickbirch**
Updated text based on Igor's comments.

### CODE REVIEW

**Review by igorsol — APPROVED** [review]

**Comment by patrickbirch** [comment]
Added a commit that clarifies the support for V2 API versioning must be enabled.

**Review by tplavcic — CHANGES_REQUESTED** [review]
I don't see key rotation steps?

**Comment by patrickbirch** [comment]
Added rotation steps.

**Review by tplavcic — APPROVED** [review]
LGTM

**Pull request merged**
